### ISSUE TITLE
is an array sufficient for the movies in a user list. should this be an object instead? 

### ISSUE THREAD

**Issue by cgefx** [chingu-voyages/v21-geckos-team-03#44]

**Comment by BFrancoeur** [comment]
Hi Collin, they probably should be objects, since we're adding multiple
properties.

**Comment by cgefx** [comment]
when we first started thinking through this i think we dicussed just saving the imdbId in an array, and then calling the api again to populate the list.  

i guess it still probably needs other properties.

maybe watched (boolean), added(date), imdbID, rating 

anything else?

**Comment by Rayhan1998** [comment]
I was thinking an array with the Movie ID that the API gives us. With that movie ID We pretty much can get any information on a particular movie.

**Comment by cgefx** [comment]
we should get a path for this ironed out tomorrow.  feel like there are gremlins in the details on how this will work.

**Comment by cgefx** [comment]
moved discussion to issue #47
