### ISSUE TITLE
Determine how much/which info from each movie in the API to save in firebase

### ISSUE THREAD

**Issue by marshallhelenm** [chingu-voyages/v21-geckos-team-03#47]

**Comment by cgefx** [comment]
initial thoughts:

from api ( not actual property names for now):
- movie title
- release year
- director 
- imdb ID ( whatever will allow a link back to the full movie page)
- imdb rating
- genre
- short description ( i think this is called overview)
- url to poster thumbnail if possible without having to call api to retrieve. 

not from api (user added data)
- watched ( boolean - maybe this hides movies that were watched so they dont need to be deleted afterwards),
-  timestamp when watched
- date added to list
- user review
- user rating
