### ISSUE TITLE
Redundant / Overlapping Components

### ISSUE THREAD

**Issue by cgefx** [chingu-voyages/v21-geckos-team-03#58]
Noticed these files overlap in functionality: 

MovieCard / SearchResult / SearchPanel/SearchMovie / SearchResults

SearchMovie and MovieCard are the only files that contain functionality.  

Artifacts from the previous repo and I Can't recall who wrote what.

 Need to remove any redundant / unnecessary ones at some point and make sure we are on the same page with which are being used...

**Comment by marshallhelenm** [comment]
I made most of those as stubs to be filled in. It looks like SearchMovie contains a lot of functionality. @Rayhan1998 if it's ok with you, I would like to split out the functionality in SearchMovie into several different components. A couple of them could then be reused elsewhere. I've got an idea of how to go about it but don't want to step on your toes so let me know what you think.

**Comment by Rayhan1998** [comment]
Im okay with that El. Go on ahead.
