### ISSUE TITLE
bug: refactor firestore db calls to use onSnapshot instead of get

### ISSUE THREAD

**Issue by cgefx** [chingu-voyages/v21-geckos-team-03#59]
onSnapshot sets up an observer so updates to the db will trigger state changes in the UI without needing to reload.

**Comment by cgefx** [comment]
pretty clean looking examples here.  see fetching a document and fetching collection sections.

https://benmcmahen.com/using-firebase-with-react-hooks/

**Comment by marshallhelenm** [comment]
Can this be closed?

**Comment by cgefx** [comment]
yup just did
