### ISSUE TITLE
Create wireframes for app page views

### ISSUE THREAD

**Issue by cgefx** [chingu-voyages/v21-geckos-team-03#6]
- [x] search for movie page ( home?)
- [x] single watch list 
- [x] sign-in / sign-up
- [x] single movie view
- [x] All lists view

**Comment by cgefx** [comment]
@chingu-voyages/v21-geckos-team-03 

Just spent a little time on this.  Please take a look and comment when you can so we can get everyone on the same page layout wise.

Here's the link to the Sketch cloud document:  [Movie-app-wireframes](https://www.sketch.com/s/7a10fe15-79a3-4bad-ac7c-a94f32a47494).

Obviously this is super super rough design wise - just focusing on the form/filter/search flow for now.

A few things came to mind while doing this:
1. does clicking "search" redirect to a new page which loads the results, or the results load below with no redirect.
2. is this search page also the home page? or do we need a landing page first?

**Comment by Rayhan1998** [comment]
I was thinking initially having the search bar in the middle and after the user searches for a movie, the search bar transitions up and the results slowly eases up. In a sense pushing the search bar up.

**Comment by cgefx** [comment]
@Rayhan1998  - basically exactly like this then right?

 https://rainbow-algolia-search.web.app/

but instead of the pagination that appears after text input, thats where the filter menu bar is?

**Comment by Rayhan1998** [comment]
@cgefx Yes very similar. But lets say for example a user searches BATMAN and 20 results show up. Are we going to keep the results all in one page in a 3x3 layout or so. Or are we going to have a previous and next page button?

**Comment by cgefx** [comment]
good question.  I'm looking at your code from using the API.  It looks like requests come back in pages?  Seems like infinite scroll or pagination are both natural options.  

I'm always split on this one.  On one hand having to click for another page is annoying, but infinite scroll destroys brains!  

@BFrancoeur @marshallhelenm any opinions?  

I think my vote goes for infinite scroll since I think it can be a little more mobile friendly.

**Comment by Rayhan1998** [comment]
Im okay with infinite scroll but if we have infinite scroll, I think it's best to have a row and column setup. Maybe 3x3 or 4x4 because if we have a 1x1 there might be a lot of scrolling.

**Comment by Rayhan1998** [comment]
I'm okay with infinite scroll but if we have infinite scroll, I think it's best to have a row and column setup. Maybe 3x3 or 4x4 because if we have a 1x1 there might be a lot of scrolling.

**Comment by cgefx** [comment]
just glanced at the API docs. Looks like there isn't a way to limit the number of responses per page.  Do you know how many come back per?  Tried to check your app but seems to be down at the moment... 

Anything more than 2 columns is going to be really hard on mobile, even 2 may be cramped unless we really shrink things down.  

Maybe pagination is the move then?

**Comment by Rayhan1998** [comment]
Each page hold 20 results. I searched batman and about 6 pages came up. So over 100 results.

**Comment by Rayhan1998** [comment]
Also on mobile we can just have 1 column per row. Basically adjust it per screen size. Thats what I did with my app.

**Comment by marshallhelenm** [comment]
General layout seems good to me. Are we going to have a modal with more info on click, or direct to a new page?

**Comment by Rayhan1998** [comment]
I was thinking after we click on the movie it goes to a new page displaying info, trailer,review,actors etc.

**Comment by cgefx** [comment]
yup @Rayhan1998 thats what I was thinking as well.  

But also in the list view, each card has small drop down menu for quick actions.  Add / remove to list as a first step then maybe add to new list, move to another list, ect...

**Comment by cgefx** [comment]
back at it working on all of this today.

**Comment by cgefx** [comment]
@marshallhelenm @BFrancoeur @Rayhan1998 

This has been stalled for some time in my backlog.   My Sketch / UI design skills are just too lacking to get this done in time for it to be useful to the project. 

But.. im sensing we are all might be a little in the dark about UI direction as our pages come together and this could be blocking work.

How does everyone else feel about this?  

If we agree that wireframes are still necessary for some views I would take a day to learn [Balsamic](https://balsamiq.com/) and make it priority one.  Otherwise we'll just have to take care to talk through ui decisions as we go.

Why i've been trying to wireframe in sketch is beyond me 🤦🏻‍♂️  -  balsamic is clearly the tool for the job.

**Comment by marshallhelenm** [comment]
I personally think we just need very basic wireframes. Heck, I'd be satisfied with sketches on a piece of paper/whiteboard. It's a pretty simple app, so I think so long as we consult with each other before making any radical changes to things someone else has worked on/is working on, we should be ok.

**Comment by cgefx** [comment]
agreed.  i spent about an hour with balsamic today and think it can get us what we need quick and dirty.
