### ISSUE TITLE
Sign off on remaining team decisions

### ISSUE THREAD

**Issue by cgefx** [chingu-voyages/v21-geckos-team-03#9]
- [x] What is our highest level team goal for the project.
- [x] Final MVP features we are aiming for.
- [x] What is the name of the app??

**Comment by marshallhelenm** [comment]
Name proposals:
Flick List
Flickz
Flick
Reel
UnReel (personal favorite of these i think)
SilverList
Backlog

**Comment by cgefx** [comment]
UnReel is pretty solid for sure.  

Only addition I could come up with is "B-Roll"

 @BFrancoeur @Rayhan1998 you guys have any to add?

**Comment by Rayhan1998** [comment]
I like UnReel, it has a nice sound to it.

**Comment by marshallhelenm** [comment]
Seems these are all good. We've got our eye on MVP and have agreed to UnReel as the name.
